"""
Deploy OpenShift cluster using kcli.
Supports both local and remote libvirt hosts.
Default topology is SNO (Single Node OpenShift): 1 control plane, 0 workers.
"""

import base64
import json
import shlex
import shutil
import subprocess
import threading
import time
from pathlib import Path
from typing import Any, Callable, Dict, List, Optional

from common import DeployError, run
from config import get_cluster_topology_description
from kcli_preflight import ensure_kcli_installed, ensure_pull_secret_exists, ensure_kcli_config


def patch_bootstrap_ignition(cluster_name: str) -> bool:
    """Fix OCP release image URL bug in bootstrap.ign.

    Some OCP versions ship release-image.sh with:
        quay.io/openshift-release-dev:<VERSION>-x86_64
    instead of the correct repository-qualified form:
        quay.io/openshift-release-dev/ocp-release:<VERSION>-x86_64

    The file is regenerated by kcli on every deploy, so this must run
    after kcli creates bootstrap.ign but before the bootstrap VM boots.
    Returns True if the file was found (and patched if needed), False if not yet present.
    """
    ign_path = Path.home() / ".kcli" / "clusters" / cluster_name / "bootstrap.ign"
    if not ign_path.exists():
        return False

    wrong = b"quay.io/openshift-release-dev:"
    correct = b"quay.io/openshift-release-dev/ocp-release:"

    try:
        data = json.loads(ign_path.read_text())
    except (json.JSONDecodeError, OSError) as e:
        print(f"  bootstrap.ign patch: failed to parse JSON: {e}")
        return False

    patched_count = 0
    for item in data.get("storage", {}).get("files", []):
        contents = item.get("contents", {})
        source = contents.get("source", "")
        if not source.startswith("data:text/plain;base64,"):
            continue
        raw = base64.b64decode(source[len("data:text/plain;base64,"):])
        if wrong in raw:
            fixed = raw.replace(wrong, correct)
            contents["source"] = "data:text/plain;base64," + base64.b64encode(fixed).decode()
            patched_count += 1

    if patched_count > 0:
        ign_path.write_text(json.dumps(data))
        print(f"  bootstrap.ign patched: fixed release image URL in {patched_count} file(s).")
    else:
        print("  bootstrap.ign: release image URL already correct, no patch needed.")

    return True


def patch_remote_bootstrap_ignition(host: str, user: str) -> bool:
    """Patch the release image URL in kcli's remote bootstrap ignition file.

    kcli generates release-image.sh / release-image-download.sh with:
        RELEASE_IMAGE=quay.io/openshift-release-dev:<VERSION>-x86_64
    which is a 404.  The correct path includes /ocp-release.

    These scripts are gzip-compressed inside /home/libvirt/images/ocp-bootstrap.ign
    on the remote libvirt host.  Returns True if the file was found (and patched
    if needed), False if not yet present.
    """
    from shared.ssh import ssh_cmd

    remote_path = "/home/libvirt/images/ocp-bootstrap.ign"

    r = ssh_cmd(host, user, f"test -f {remote_path} && echo exists || echo missing", check=False)
    if "exists" not in (r.stdout or ""):
        return False

    patch_script = r"""
import json, base64, gzip, sys

wrong   = b'quay.io/openshift-release-dev:'
correct = b'quay.io/openshift-release-dev/ocp-release:'

path = '/home/libvirt/images/ocp-bootstrap.ign'
data = json.loads(open(path).read())

patched = 0
for f in data.get('storage', {}).get('files', []):
    src = f.get('contents', {}).get('source', '')
    if 'base64,' not in src:
        continue
    b64   = src.split('base64,', 1)[1]
    raw   = base64.b64decode(b64)
    is_gz = raw[:2] == b'\x1f\x8b'
    dec   = gzip.decompress(raw) if is_gz else raw
    if wrong not in dec:
        continue
    fixed     = dec.replace(wrong, correct)
    reencoded = gzip.compress(fixed) if is_gz else fixed
    prefix    = src.split('base64,')[0]
    f['contents']['source'] = prefix + 'base64,' + base64.b64encode(reencoded).decode()
    patched += 1

if patched:
    open(path, 'w').write(json.dumps(data))
    print('remote bootstrap.ign patched: fixed release image URL in', patched, 'file(s).')
else:
    print('remote bootstrap.ign: release image URL already correct.')
"""

    r = ssh_cmd(host, user, f"python3 -c {shlex.quote(patch_script)}", check=False)
    if r.returncode != 0:
        print(f"  remote bootstrap.ign patch failed: {(r.stderr or r.stdout or '').strip()}")
        return False
    msg = (r.stdout or "").strip()
    if msg:
        print(f"  {msg}")
    return True


def push_ssh_key_to_remote(host: str, user: str) -> None:
    """Copy the CI runner's SSH private key to the remote host.

    kcli injects the CI runner's public key into VMs, but the remote host
    needs the matching private key to SSH into its own VMs.
    Copies all common key types so the remote host can reach the VMs
    regardless of which key kcli injected.
    """
    from shared.ssh import ssh_key_path, scp_cmd, ssh_cmd

    local_key = Path(ssh_key_path) if ssh_key_path else Path.home() / ".ssh" / "id_rsa"
    if not local_key.exists():
        print("  No SSH key to push — skipping.")
        return

    print("Copying SSH key to remote host for VM access")
    scp_cmd(str(local_key), f"{user}@{host}:/root/.ssh/id_rsa")
    ssh_cmd(host, user, "chmod 600 /root/.ssh/id_rsa", check=False)
    ssh_cmd(
        host, user,
        "ssh-keygen -y -f /root/.ssh/id_rsa > /root/.ssh/id_rsa.pub 2>/dev/null",
        check=False,
    )

    # Also copy ed25519 key — kcli typically injects whichever key type it finds first,
    # and recent kcli versions prefer ed25519.
    ed25519_key = Path.home() / ".ssh" / "id_ed25519"
    if ed25519_key.exists():
        scp_cmd(str(ed25519_key), f"{user}@{host}:/root/.ssh/id_ed25519")
        ssh_cmd(host, user, "chmod 600 /root/.ssh/id_ed25519", check=False)


def patch_bootstrap_vm_scripts(host: str, user: str, cluster_name: str) -> None:
    """SSH into the bootstrap VM and fix the kcli-generated release image URL.

    kcli embeds the wrong URL (missing /ocp-release) in release-image*.sh via
    the ignition ISO. The scripts land on disk during first boot and are read
    by node-image-pull.service on every retry. This function patches them in
    place and restarts the service so it picks up the fix.
    """
    from shared.ssh import ssh_cmd

    wrong   = r"quay.io/openshift-release-dev:"
    correct = r"quay.io/openshift-release-dev/ocp-release:"

    # Try keys in order of what kcli typically injects
    vm_keys = ["/root/.ssh/id_ed25519", "/root/.ssh/id_rsa"]

    # Find bootstrap VM IP via DHCP leases
    print("\nStep 5d: Patching bootstrap VM release image URL...")
    bootstrap_ip = None
    for _ in range(36):  # 6 minutes
        r = ssh_cmd(
            host, user,
            f"virsh net-dhcp-leases default 2>/dev/null | grep '{cluster_name}-bootstrap' "
            f"| tail -1 | awk '{{print $5}}' | cut -d/ -f1",
            check=False,
        )
        ip = (r.stdout or "").strip()
        if ip:
            bootstrap_ip = ip
            break
        time.sleep(10)

    if not bootstrap_ip:
        print("  Could not find bootstrap VM IP — skipping script patch.")
        return

    print(f"  Bootstrap VM IP: {bootstrap_ip}")

    # Wait for SSH to be ready
    vm_key = None
    for _ in range(30):  # 5 minutes
        for key in vm_keys:
            r = ssh_cmd(
                host, user,
                f"ssh -i {key} -o StrictHostKeyChecking=no -o ConnectTimeout=5 "
                f"core@{bootstrap_ip} 'echo ok' 2>/dev/null",
                check=False,
            )
            if "ok" in (r.stdout or ""):
                vm_key = key
                break
        if vm_key:
            break
        time.sleep(10)

    if not vm_key:
        print("  SSH to bootstrap VM not available — skipping script patch.")
        return

    # Use base64-encoded Python to avoid shell quoting issues with | in sed expressions.
    # The | delimiter gets misinterpreted as a pipe by the bootstrap VM's shell when
    # passed through double SSH hops with naive quoting.
    import base64
    patch_py = (
        "import subprocess,os\n"
        f"w={wrong!r}\n"
        f"c={correct!r}\n"
        "for p in['/usr/local/bin/release-image.sh','/usr/local/bin/release-image-download.sh']:\n"
        "    if not os.path.exists(p):continue\n"
        "    t=open(p).read()\n"
        "    if w in t:open(p,'w').write(t.replace(w,c))\n"
        "subprocess.run(['systemctl','restart','node-image-pull.service'])\n"
        "print('patched')\n"
    )
    b64 = base64.b64encode(patch_py.encode()).decode()
    r = ssh_cmd(
        host, user,
        f"ssh -i {vm_key} -o StrictHostKeyChecking=no core@{bootstrap_ip} "
        f'"echo {b64} | base64 -d | sudo python3"',
        check=False,
    )
    if "patched" in (r.stdout or ""):
        print("  Bootstrap VM: release image URL patched and node-image-pull restarted.")
    else:
        print(f"  Bootstrap VM: patch attempt: {(r.stdout or '').strip() or '(no output)'}")


def fix_vm_container_storage(
    host: str, user: str, cluster_name: str, ctlplanes: int
) -> None:
    """Wipe pre-baked container storage on RHCOS VMs via guestfish.

    Works around a composefs/overlay bug where ``podman pull`` fails with
    ``readlink /var/lib/containers/storage/overlay/l: invalid argument``.

    The RHCOS qcow2 image ships pre-baked overlay layers that are
    incompatible with fresh podman pulls when used through kcli's
    qcow2-on-qcow2 overlay. Wiping the directory lets the
    ``machine-config-daemon-pull`` service succeed.

    The VMs must be shut off before calling this function.
    """
    from shared.ssh import ssh_cmd

    print("\nStep 5c: Fixing RHCOS container storage (composefs overlay workaround)...")

    r = ssh_cmd(host, user, "command -v guestfish", check=False)
    if r.returncode != 0:
        print("  Installing libguestfs-tools on remote host...")
        ssh_cmd(host, user, "dnf -y install libguestfs-tools-c", check=False, timeout=300)

    storage_path = "/ostree/deploy/rhcos/var/lib/containers/storage"

    for idx in range(ctlplanes):
        vm_name = f"{cluster_name}-ctlplane-{idx}"

        r = ssh_cmd(host, user, f"virsh domstate {vm_name}", check=False)
        if "shut off" not in (r.stdout or ""):
            print(f"{vm_name}: VM is not shut off — skipping.")
            continue

        gf_script = f"run\nmount /dev/sda4 /\nglob rm-rf {storage_path}/*\n"
        r = ssh_cmd(host, user, f"echo '{gf_script}' | guestfish --rw -d {vm_name}", check=False, timeout=120)
        if r.returncode == 0:
            print(f"{vm_name}: container storage wiped.")
        else:
            print(f"    {vm_name}: guestfish failed (rc={r.returncode}): "
                  f"{(r.stderr or '').strip()}")


def shutdown_vms(host: str, user: str, cluster_name: str, ctlplanes: int) -> None:
    """Shut down control plane VMs and wait for them to be off."""
    from shared.ssh import ssh_cmd

    for idx in range(ctlplanes):
        vm_name = f"{cluster_name}-ctlplane-{idx}"
        ssh_cmd(host, user, f"virsh shutdown {vm_name}", check=False)

    for idx in range(ctlplanes):
        vm_name = f"{cluster_name}-ctlplane-{idx}"
        for _ in range(24):
            time.sleep(5)
            r = ssh_cmd(host, user, f"virsh domstate {vm_name}", check=False)
            if "shut off" in (r.stdout or ""):
                print(f"  {vm_name} shut off.")
                break
        else:
            ssh_cmd(host, user, f"virsh destroy {vm_name}", check=False)
            time.sleep(2)


def start_vms(host: str, user: str, cluster_name: str, ctlplanes: int) -> None:
    """Start control plane VMs."""
    from shared.ssh import ssh_cmd

    for idx in range(ctlplanes):
        vm_name = f"{cluster_name}-ctlplane-{idx}"
        ssh_cmd(host, user, f"virsh start {vm_name}", check=False)
        print(f"  {vm_name} started.")


def build_kcli_params(params: Dict[str, str]) -> List[str]:
    """
    Build kcli -P parameter arguments from params dict.
    
    Returns:
        List of ["-P", "key=value", "-P", "key2=value2", ...]
    """
    args = []
    for key, value in params.items():
        args.extend(["-P", f"{key}={value}"])
    return args


def deploy_cluster(
    params: Dict[str, Any],
    remote_host: Optional[str],
    remote_user: str,
    wait_timeout: int,
    ssh_key: Optional[str],
    pci_devices: Optional[List[str]],
) -> None:
    """
    Main deployment flow, driven by the kcli parameters.

    Deploys the cluster and waits for it to be ready. Does NOT install
    operators or run tests — use the separate 'operators' and 'test-gpu'
    commands for those.

    Args:
        params: Parameters dictionary (from config.get_kcli_params)
        remote_host: Remote libvirt host (None for local deployment)
        remote_user: SSH user for remote host
        wait_timeout: Timeout in seconds for cluster ready (remote only)
        ssh_key: Path to SSH private key file (optional)
        pci_devices: List of PCI device addresses for passthrough (e.g., ["0000:b3:00.0"])
    """
    ensure_kcli_installed()
    
    cluster_name = params["cluster"]
    api_ip = params["api_ip"]
    domain = params["domain"]
    ctlplanes = int(params["ctlplanes"])
    workers = int(params["workers"])

    # Remove existing kcli cluster artifacts directory, if present
    clusters_dir = Path.home() / ".kcli" / "clusters" / cluster_name
    if clusters_dir.is_dir():
        print(f"Removing existing kcli cluster artifacts directory: {clusters_dir}")
        shutil.rmtree(clusters_dir)

    pull_secret_path_str = params.get("pull_secret", "")
    if not pull_secret_path_str:
        raise DeployError("Missing 'pull_secret' in parameters.")
    pull_secret_path = Path(pull_secret_path_str)

    ensure_pull_secret_exists(pull_secret_path)

    # Handle remote vs local deployment
    if remote_host:
        deploy_remote(
            params=params,
            cluster_name=cluster_name,
            api_ip=api_ip,
            domain=domain,
            ctlplanes=ctlplanes,
            workers=workers,
            remote_host=remote_host,
            remote_user=remote_user,
            wait_timeout=wait_timeout,
            ssh_key=ssh_key,
            pci_devices=pci_devices,
        )
    else:
        deploy_local(
            params=params,
            ctlplanes=ctlplanes,
            workers=workers,
        )


def deploy_local(
    params: Dict[str, Any],
    ctlplanes: int,
    workers: int,
) -> None:
    """Deploy OpenShift cluster locally using kcli."""
    ensure_kcli_config()

    cluster_name = params["cluster"]
    topology = get_cluster_topology_description(ctlplanes, workers)

    # Build kcli command with all parameters via -P flags
    kcli_cmd = ["kcli", "create", "cluster", "openshift"]
    kcli_cmd.extend(build_kcli_params(params))

    print(f"\nStarting OpenShift deployment [{topology}] with kcli...")
    print(f"  kcli command: {' '.join(kcli_cmd)}")

    kcli_process = subprocess.Popen(
        kcli_cmd,
        stdout=subprocess.PIPE,
        stderr=subprocess.STDOUT,
        text=True,
    )

    def _stream_kcli(proc: subprocess.Popen) -> None:
        for line in iter(proc.stdout.readline, ""):
            print(f"[kcli] {line}", end="", flush=True)

    threading.Thread(target=_stream_kcli, args=(kcli_process,), daemon=True).start()

    # Patch bootstrap.ign as soon as kcli generates it — same URL bug applies locally.
    ign_patch_timeout = 300
    ign_wait_start = time.time()
    local_patched = False
    while not local_patched and kcli_process.poll() is None:
        local_patched = patch_bootstrap_ignition(cluster_name)
        if local_patched:
            print("  Local bootstrap.ign processed.")
            break
        elapsed = int(time.time() - ign_wait_start)
        if elapsed >= ign_patch_timeout:
            print(f"  Timeout waiting for bootstrap.ign ({elapsed}s) — skipping patch.")
            break
        time.sleep(2)

    kcli_process.wait()
    if kcli_process.returncode != 0:
        raise DeployError(f"kcli deployment failed with exit code {kcli_process.returncode}")

    print(f"\nOpenShift deployment [{topology}] command has completed.")
    print("Check 'kcli list' and the OpenShift console once the cluster is fully up.")


def deploy_remote(
    params: Dict[str, Any],
    cluster_name: str,
    api_ip: str,
    domain: str,
    ctlplanes: int,
    workers: int,
    remote_host: str,
    remote_user: str,
    wait_timeout: int,
    ssh_key: Optional[str] = None,
    pci_devices: Optional[List[str]] = None,
) -> None:
    """Deploy OpenShift cluster on a remote libvirt host."""
    from remote import (
        setup_remote_libvirt,
        configure_kcli_remote_client,
        setup_remote_cluster_access,
        wait_for_cluster_ready,
        get_cluster_status,
        print_access_instructions,
        set_ssh_key_path,
        attach_pci_devices,
    )
    
    topology = get_cluster_topology_description(ctlplanes, workers)
    
    if ssh_key:
        set_ssh_key_path(ssh_key)
        print(f"Using SSH key: {ssh_key}")
    
    print(f"\n{'='*60}")
    print(f"Remote OpenShift Deployment [{topology}]")
    print(f"{'='*60}")
    print(f"Remote Host: {remote_user}@{remote_host}")
    print(f"Cluster Name: {cluster_name}")
    print(f"Topology: {topology}")
    print(f"API IP: {api_ip}")
    print(f"Domain: {domain}")
    print(f"Wait Timeout: {wait_timeout}s")
    if ssh_key:
        print(f"SSH Key: {ssh_key}")
    print(f"{'='*60}\n")

    # Step 1: Setup remote host (idempotent)
    print("Step 1: Setting up remote host...")
    setup_remote_libvirt(remote_host, remote_user)

    # Step 2: Configure kcli client
    print("\nStep 2: Configuring kcli client...")
    kcli_client = configure_kcli_remote_client(remote_host, remote_user)

    # Step 3: Clean up any existing cluster
    print(f"\nStep 3: Cleaning up any existing cluster '{cluster_name}'...")
    run(["kcli", "-C", kcli_client, "delete", "cluster", cluster_name, "--yes"], check=False)
    clusters_dir = Path.home() / ".kcli" / "clusters" / cluster_name
    if clusters_dir.is_dir():
        shutil.rmtree(clusters_dir)
    # Remove cached openshift-install binary on the remote host so kcli always
    # downloads the correct version matching the requested tag (prevents stale
    # installer from a previous deploy being reused with a different OCP tag).
    from shared.ssh import ssh_cmd
    ssh_cmd(remote_host, remote_user,
            "rm -f /root/.kcli/openshift-install /root/.kcli/openshift-install-* "
            "/root/.kcli/oc /root/.kcli/kubectl",
            check=False)
    print("  Cleared remote kcli installer cache.")
    # Remove stale ignition files left behind by `kcli delete cluster`.
    # kcli deletes VM disks but NOT .ign files; a new deploy reuses the
    # stale file (wrong certs/credentials) and bootstrap never succeeds.
    ssh_cmd(remote_host, remote_user,
            "rm -f /home/libvirt/images/ocp-bootstrap.ign "
            "/home/libvirt/images/ocp-ctlplane-*.ign",
            check=False)
    print("  Cleared stale ignition files from libvirt storage pool.")
    
    # Step 4: Deploy the cluster
    print(f"\nStep 4: Deploying OpenShift cluster [{topology}]...")
    print("Starting kcli deployment (monitoring will be done via remote host)...")
    
    kcli_cmd = ["kcli", "-C", kcli_client, "create", "cluster", "openshift"]
    kcli_cmd.extend(build_kcli_params(params))
    
    print(f"  kcli command: {' '.join(kcli_cmd)}")
    print("\n  Starting kcli in background...")
    
    kcli_process = subprocess.Popen(
        kcli_cmd,
        stdout=subprocess.PIPE,
        stderr=subprocess.STDOUT,
        text=True,
    )

    def _stream_kcli(proc: subprocess.Popen) -> None:
        for line in iter(proc.stdout.readline, ""):
            print(f"[kcli] {line}", end="", flush=True)

    threading.Thread(target=_stream_kcli, args=(kcli_process,), daemon=True).start()

    expected_vms = ctlplanes + workers + 1
    min_vms_to_proceed = 2

    # Step 4b: Patch bootstrap.ign files (local + remote) as soon as they appear.
    # kcli generates release-image*.sh with a wrong release image URL; both the
    # local openshift-install copy and kcli's own remote copy must be fixed.
    print("\nStep 4b: Watching for bootstrap.ign files to patch release image URL...")
    ign_patch_timeout = 300
    ign_wait_start = time.time()
    local_patched = False
    remote_patched = False
    while not (local_patched and remote_patched):
        if kcli_process.poll() is not None:
            print("  kcli exited before all bootstrap.ign files appeared — skipping remaining patches.")
            break
        if not local_patched:
            local_patched = patch_bootstrap_ignition(cluster_name)
            if local_patched:
                print("  Local bootstrap.ign processed.")
        if not remote_patched:
            remote_patched = patch_remote_bootstrap_ignition(remote_host, remote_user)
            if remote_patched:
                print("  Remote bootstrap.ign processed.")
        if local_patched and remote_patched:
            break
        elapsed = int(time.time() - ign_wait_start)
        if elapsed >= ign_patch_timeout:
            print(f"  Timeout waiting for bootstrap.ign files ({elapsed}s) — skipping remaining patches.")
            break
        if elapsed % 30 == 0:
            print(f"  Waiting for bootstrap.ign... ({elapsed}s, local={local_patched}, remote={remote_patched})")
        time.sleep(2)

    # Step 5: Wait for VMs to be deployed
    print("\nStep 5: Waiting for VMs to be deployed...")
    vm_wait_timeout = 600
    vm_wait_start = time.time()
    while True:
        if kcli_process.poll() is not None:
            if kcli_process.returncode != 0:
                print(f"\n✗ kcli process exited with code {kcli_process.returncode}")
                raise DeployError(f"kcli deployment failed with exit code {kcli_process.returncode}")
        
        result = run(["kcli", "-C", kcli_client, "list", "vm"], check=False, capture_output=True)
        vm_count = result.stdout.count(f"{cluster_name}-")
        
        if vm_count >= min_vms_to_proceed:
            print(f"  VMs deployed: {vm_count} VMs found (expecting {expected_vms} total)")
            break
        
        elapsed = int(time.time() - vm_wait_start)
        if elapsed >= vm_wait_timeout:
            try:
                kcli_process.terminate()
                kcli_process.wait(timeout=5)
            except Exception:
                pass
            raise DeployError("Timeout waiting for VMs to be deployed (10 minutes)")
        
        if elapsed % 30 == 0 or vm_count > 0:
            print(f"  Waiting for VMs... ({elapsed}s elapsed, found {vm_count} VMs, expecting {expected_vms})")
        time.sleep(10)
    
    print("\nVMs on remote host:")
    run(["kcli", "-C", kcli_client, "list", "vm"], check=False)

    push_ssh_key_to_remote(remote_host, remote_user)

    # Step 5b/5c: PCI attachment + container storage fix.
    # Both need the VM shut off. When PCI devices are requested the
    # attach_pci_devices helper already shuts down the VM, so we hook
    # the storage fix into that window via pre_start_hook. Without PCI
    # devices we shut down/start the VMs ourselves.
    if pci_devices:
        print("\nStep 5b: Attaching PCI devices to control plane VM...")
        ctlplane_vm = f"{cluster_name}-ctlplane-0"
        attach_pci_devices(
            remote_host, remote_user, ctlplane_vm, pci_devices,
            pre_start_hook=lambda: fix_vm_container_storage(
                remote_host, remote_user, cluster_name, ctlplanes),
        )
    else:
        shutdown_vms(remote_host, remote_user, cluster_name, ctlplanes)
        fix_vm_container_storage(remote_host, remote_user, cluster_name, ctlplanes)
        start_vms(remote_host, remote_user, cluster_name, ctlplanes)

    # Step 5d: Patch bootstrap VM release image scripts.
    # The ignition is baked into an ISO (ocp-bootstrap.ISO) before the VM boots,
    # so patching the .ign file is too late. We SSH into the running bootstrap VM
    # after the container-storage-fix restart and patch the scripts in place.
    patch_bootstrap_vm_scripts(remote_host, remote_user, cluster_name)

    # Step 6: Setup remote cluster access
    print("\nStep 6: Setting up remote cluster access...")
    setup_remote_cluster_access(remote_host, remote_user, cluster_name, api_ip, domain)
    
    # Kill kcli process
    print("\nStopping kcli monitoring (we'll monitor via remote host)...")
    kcli_process.terminate()
    try:
        kcli_process.wait(timeout=10)
    except subprocess.TimeoutExpired:
        kcli_process.kill()
    
    # Step 7: Wait for cluster to be ready
    print(f"\nStep 7: Waiting for cluster to be ready...")
    wait_for_cluster_ready(remote_host, remote_user, api_ip, wait_timeout)

    # Step 7b: Sync kubeconfig from remote back to local.
    # setup_remote_cluster_access() runs before kcli writes fresh credentials,
    # so it may have copied a stale previous-cluster kubeconfig to the remote.
    # wait_for_cluster_ready() confirmed the remote /root/kubeconfig works —
    # copy it back so local tests (pytest, conftest.py) use current credentials.
    print("\nStep 7b: Syncing kubeconfig from remote to local...")
    from shared.ssh import scp_cmd as _scp
    local_kc = Path.home() / ".kcli" / "clusters" / cluster_name / "auth" / "kubeconfig"
    local_kc.parent.mkdir(parents=True, exist_ok=True)
    _scp(f"{remote_user}@{remote_host}:/root/kubeconfig", str(local_kc))
    print(f"  Kubeconfig synced from remote to {local_kc}")

    # Final status
    print("\n" + "=" * 60)
    print("CLUSTER STATUS")
    print("=" * 60)
    status = get_cluster_status(remote_host, remote_user)
    print(status)
    
    print_access_instructions(
        host=remote_host,
        user=remote_user,
        cluster_name=cluster_name,
        api_ip=api_ip,
        domain=domain,
        kcli_client=kcli_client,
    )

    print("\nDeployment completed successfully!")
